# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
version: "3"

services:
  ldap:
    container_name: ldap
    environment:
        LDAP_FORCE_STARTTLS: "false"
        LDAP_DOMAIN: "planetexpress.com"
        LDAP_BASEDN: "dc=planetexpress,dc=com"
          #LDAP_ORGANISATION: "Custom Domain, Inc."
        LDAP_BINDDN: "cn=admin,dc=planetexpress,dc=com"
        LDAP_ADMIN_USERNAME: "admin"
        LDAP_ADMIN_PASSWORD: "GoodNewsEveryone"
    build:
        context: ./
        dockerfile: ./Dockerfile.openldap
          #      ports:
          #          - '10389:10389'
          #          - '10636:10636'
    networks:
      - jupyterhub-network
  hub:
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: latest
    restart: always
    image: jupyterhub
    container_name: jupyterhub-ldap
    networks:
      - jupyterhub-network
    volumes:
      # The JupyterHub configuration file
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "jupyterhub-data:/data"
    ports:
      - "8000:8000"
    environment:
      # This username will be a JupyterHub admin
      JUPYTERHUB_ADMIN: admin
      # All containers will join this network
      DOCKER_NETWORK_NAME: jupyterhub-network
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: jupyter/base-notebook:latest
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work
      # Using this run command
      DOCKER_SPAWN_CMD: start-singleuser.sh

volumes:
  jupyterhub-data:

networks:
  jupyterhub-network:
    name: jupyterhub-network
